#spring boot application name and driver to mysql
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_test
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  #database especification
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  defer-datasource-initialization: true

