spring:
  # define active profile
  profiles:
    active: test
  application:
    name: test-rest-spring
  #this property is used to defer the datasource initialization
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
