#spring boot application name and driver to h2
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  #database especification
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
         dialect: org.hibernate.dialect.H2Dialect
  defer-datasource-initialization: true

  
